FROM node:18-alpine

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the rest of the source code
COPY . .

# Expose backend port
EXPOSE 5000

# Run the app
CMD ["node", "index.js"]
